### ISSUE TITLE
Unable to install Android Emulator Hypervisor Driver for AMD Processors

### ISSUE THREAD

**Issue by prashantkr006** [google/android-emulator-hypervisor-driver-for-amd-processors#64]
even the virtualization is enabled still couldn't install Android Emulator Hypervisor Driver for AMD Processors
![image](https://user-images.githubusercontent.com/54601213/131278903-48681816-3316-4357-85b0-bf333fa65fe0.png)

**Comment by adligo** [comment]
I think I opened a similar issue, that I was able to fix by changing this SVM bios setting and then reinstalling android studio.
![20210904_194214](https://user-images.githubusercontent.com/6592521/132111460-331d61dd-7a0c-49a4-8e6b-a22027674a51.jpg)

**Comment by IoTFier** [comment]
Hi @adligo , I am facing similar issue. The SVT is enabled on my PC.
Not sure why Android Studio needs to be reinstalled ? 
I am facing this issue on Stable as well as on Canary build (https://developer.android.com/studio/preview)

I guess the issue is really with WSL2 conflicting with this Android Emulator Hypervisor Driver for AMD Processors.
Let's hope someone from Google gives attention to this.

**Comment by adligo** [comment]
I think Android Studio detected a different processor or in my case may have had some corrupted files.  If you have a few computers, I suggest trying them.  Or try deploying to a actual phone? Good Luck :)

**Comment by IoTFier** [comment]
The following doc confirmed my doubt. It is either / or.
https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/wiki/Is-Hyper-V-really-disabled%3F
